util: Fix compiling with Android NDK
This change fixes the following compiler error.

util.cc:899:18: error: variable has incomplete type 'struct sysinfo'
  struct sysinfo si;
                 ^

C++ compiler does not define 'linux` macro with -std=c++11 which was
added in a4c24a33c1ed32d9d51c8df763ec6ad574587d02 commit. So, 'linux`
is replaced with '__linux__`. See the difference in following output.

$ clang++ -xc++ -dM -E - < /dev/null | grep linux
> #define __gnu_linux__ 1
> #define __linux 1
> #define __linux__ 1
> #define linux 1

$ clang++ -xc++ -std=c++11 -dM -E - < /dev/null | grep linux
> #define __gnu_linux__ 1
> #define __linux 1
> #define __linux__ 1